# Use this playground to experiment with list methods, using Test Run
your_courses = ["CHG331", "CHG332"]
borrowed_courses = ["CHM316", "GEG311", "PGG313"]
print(your_courses) 
print(borrowed_courses) 
borrowed_courses.append("MME211")
print(borrowed_courses)
your_courses.extend(["CHG333", "CHG334"])
print(your_courses)
borrowed_courses.insert(3, "CHM211")
print(borrowed_courses)
borrowed_courses.remove("MME211")
print(borrowed_courses)
borrowed_courses.pop(3)
print(borrowed_courses)
your_courses.index("CHG333")
print(your_courses)
your_courses.reverse()
print(your_courses)
Sss = your_courses.copy()
print(Sss)
print(len(your_courses))
print(max(your_courses, borrowed_courses))
print(min(your_courses, borrowed_courses))
print(list(range(9)))